const prompt = require('prompt-sync')()
let nrSorteado1 = Math.floor(Math.random() * 100 + 1)
let nrSorteado2 = Math.floor(Math.random()* 100 + 1)
let nrSorteado3 = Math.floor(Math.random()* 100 + 1)
let nrSorteado4 = Math.floor(Math.random()* 100 + 1)
let nrSorteado5 = Math.floor(Math.random()* 100 + 1)
let nrSorteado6 = Math.floor(Math.random()* 100 + 1)
console.log(nrSorteado1)
console.log(nrSorteado2)
console.log(nrSorteado3)
console.log(nrSorteado4)
console.log(nrSorteado5)
console.log(nrSorteado6)

console.log(`${nrSorteado1} x 2 = ${nrSorteado1 * 2}`)
console.log(`${nrSorteado2} x 2 = ${nrSorteado2 * 2}`)
console.log(`${nrSorteado3} x 2 = ${nrSorteado3 * 2}`)
console.log(`${nrSorteado4} x 2 = ${nrSorteado4 * 2}`)
console.log(`${nrSorteado5} x 2 = ${nrSorteado5 * 2}`)
console.log(`${nrSorteado6} x 2 = ${nrSorteado6 * 2}`)